function extract_feature_importances_structural()
% Extract exact feature importance numbers for the final optimized
% structural model and export the top-20 as CSV, LaTeX table and a bar plot.

assets = 'structural_model_assets.mat';
if ~isfile(assets)
    error('Assets file not found: %s', assets);
end
S = load(assets, 'optimized_model', 'selected_mask', 'poly_feature_names');
if ~isfield(S,'optimized_model') || ~isfield(S,'selected_mask') || ~isfield(S,'poly_feature_names')
    error('Missing required fields in assets file.');
end
model = S.optimized_model;
selected_mask = logical(S.selected_mask);
poly_feature_names = S.poly_feature_names;

selected_names = poly_feature_names(selected_mask);
imp = predictorImportance(model);
[imp_sorted, idx] = sort(imp, 'descend');
sel_names_sorted = selected_names(idx);

N = min(20, numel(imp_sorted));
imp_top = imp_sorted(1:N);
name_top = sel_names_sorted(1:N);
imp_total = sum(imp);
pct_top = 100 * (imp_top / max(imp_total, eps));

% CSV
writetable(table((1:N).', name_top(:), imp_top(:), pct_top(:), ...
    'VariableNames', {'rank','feature','importance','percent_of_total'}), ...
    fullfile(pwd, 'importance_top20_structural.csv'));

% LaTeX
texFile = fullfile(pwd, 'importance_top20_structural.tex');
fid = fopen(texFile, 'w');
assert(fid>0, 'Cannot open %s for writing', texFile);
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by extract_feature_importances_structural.m\n');
fprintf(fid, '\\begin{table}[h]\\n');
fprintf(fid, '\\centering\\n');
fprintf(fid, '\\begin{tabular}{r l r r}\\n');
fprintf(fid, '\\hline\\n');
fprintf(fid, 'Rank & Feature & Importance & \\%% of total \\ \n');
fprintf(fid, '\\hline\\n');
for i=1:N
    fprintf(fid, '%d & %s & %.6g & %.2f\\\\ \n', i, escape_latex(name_top{i}), imp_top(i), pct_top(i));
end
fprintf(fid, '\\hline\\n');
fprintf(fid, '\\end{tabular}\\n');
fprintf(fid, '\\caption{Top-%d feature importances (exact values) from the optimized structural ensemble.}\\n', N);
fprintf(fid, '\\label{tab:feature_importances_top20_structural}\\n');
fprintf(fid, '\\end{table}\\n');

fprintf('\nTop-%d structural feature importances (exact):\n', N);
for i=1:N
    fprintf('%2d. %-50s  imp=%g  (%.2f%%%% of total)\n', i, name_top{i}, imp_top(i), pct_top(i));
end

% Plot horizontal bar chart (largest on top)
scale = 1e3; % display importance in x10^-3 units
h = figure('Color', [0.12 0.12 0.12], 'Position', [100 100 1200 700]);
barh(imp_top * scale, 'FaceColor', [0.2 0.6 0.9], 'EdgeColor', 'none');
ax = gca;
ax.Color = [0.05 0.05 0.05];
ax.XColor = [1 1 1];
ax.YColor = [1 1 1];
ax.FontSize = 12;
ax.TickLabelInterpreter = 'none';
% Y labels (flip so largest is at top)
yticks(1:N);
yticklabels(name_top);
set(ax, 'YDir', 'reverse');
xlabel(sprintf('Predictor Importance (\\times10^{-%d})', 3), 'Color', [1 1 1]);
title('Top-20 Feature Importances (Final Optimized Structural Model)', 'Color', [1 1 1]);
grid on;
ax.GridColor = [0.3 0.3 0.3];
% Tighten x-limits a bit
xlim([0, max(imp_top) * scale * 1.05]);
% Save PNG to working folder
try
    print(h, fullfile(pwd, 'importance_top20_structural.png'), '-dpng', '-r150');
catch
    % If saving fails, ignore so script still completes for users without print support
end

end

function s = escape_latex(s)
    s = strrep(s, '\\', '\\textbackslash ');
    s = strrep(s, '_', '\\_');
    s = strrep(s, '%', '\\%%');
end
