function extract_feature_importances()
% Extract exact feature importance numbers for the final optimized model
% and export the top-20 as CSV and LaTeX table.

assets = 'architectural_model_assets.mat';
if ~isfile(assets)
    error('Assets file not found: %s', assets);
end
S = load(assets, 'optimized_model', 'selected_mask', 'poly_feature_names');
if ~isfield(S,'optimized_model') || ~isfield(S,'selected_mask') || ~isfield(S,'poly_feature_names')
    error('Missing required fields in assets file.');
end
model = S.optimized_model;
selected_mask = logical(S.selected_mask);
poly_feature_names = S.poly_feature_names;

% Reconstruct selected feature names (post-selection order)
selected_names = poly_feature_names(selected_mask);

% Compute importances
imp = predictorImportance(model);

% Sort descending
[imp_sorted, idx] = sort(imp, 'descend');
sel_names_sorted = selected_names(idx);

% Top-N (bounded by number of features)
N = min(20, numel(imp_sorted));
imp_top = imp_sorted(1:N);
name_top = sel_names_sorted(1:N);

% Percent contribution relative to total importance
imp_total = sum(imp);
if imp_total == 0
    pct_top = zeros(size(imp_top));
else
    pct_top = 100 * imp_top / imp_total;
end

% Export CSV
csvFile = fullfile(pwd, 'importance_top20.csv');
T = table((1:N).', name_top(:), imp_top(:), pct_top(:), ...
    'VariableNames', {'rank','feature','importance','percent_of_total'});
writetable(T, csvFile);

% Export LaTeX table
texFile = fullfile(pwd, 'importance_top20.tex');
fid = fopen(texFile, 'w');
assert(fid>0, 'Cannot open %s for writing', texFile);
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, '%% Auto-generated by extract_feature_importances.m\\n');
fprintf(fid, '\\begin{table}[h]\\n');
fprintf(fid, '\\centering\\n');
fprintf(fid, '\\begin{tabular}{r l r r}\\n');
fprintf(fid, '\\hline\\n');
fprintf(fid, 'Rank & Feature & Importance & \\%% of total \\\\ \\n');
fprintf(fid, '\\hline\\n');
for i=1:N
    fprintf(fid, '%d & %s & %.6g & %.2f\\\\ \\n', i, escape_latex(name_top{i}), imp_top(i), pct_top(i));
end
fprintf(fid, '\\hline\\n');
fprintf(fid, '\\end{tabular}\\n');
fprintf(fid, '\\caption{Top-%d feature importances (exact values) from the optimized ensemble.}\\n', N);
fprintf(fid, '\\label{tab:feature_importances_top20}\\n');
fprintf(fid, '\\end{table}\\n');

% Print to console as well
fprintf('\nTop-%d feature importances (exact):\n', N);
for i=1:N
    fprintf('%2d. %-50s  imp=%g  (%.2f%%%% of total)\n', i, name_top{i}, imp_top(i), pct_top(i));
end

end

function s = escape_latex(s)
% Minimal LaTeX escaping for underscores and percent
s = strrep(s, '\\', '\\textbackslash ');
s = strrep(s, '_', '\\_');
s = strrep(s, '%', '\\%%');
end
